### ISSUE TITLE
Create python example script to test a scenario using maestro2 as well.

### ISSUE THREAD

**Issue by CThuleHansen** [INTO-CPS-Association/fault-injection-maestro#4]

**Comment by gitting-around** [comment]
The branch: incubatorScenarios

**Comment by CThuleHansen** [comment]
I have created a main in the project faultinnject-incubator that accepts:
- initializeJson File
- simulateJson File
- Dump Path

It then invokes maestro2 in the correct fashion with the append FaultInject.mabl.
I have **not** created a nice CLI. (see i.e. https://github.com/INTO-CPS-Association/maestro/blob/803a94a974c31eceba8ed848a6a209035a66c3a9/maestro/src/main/java/org/intocps/maestro/MaestroV1CliProxy.java#L16 for example, if you want.
I have **not** created significant error-handling.
I have **not** decided on your plan of presenting it - Just gave an example of how to "hide" some of the internal stuff. 
Whether you follow this approach or choose something else is ENTIRELY up you.

The tests are currently failing (more info in the section __Test Fail__

To run the main function, build it from root dir with:
`mvn package -DskipTests`.  
And then execute it from `rootdir/faultinject-incubator` with:
`java -jar target/faultinject-incubator-1.0.0-SNAPSHOT-jar-with-dependencies.jar src/test/resources/multimodel.json src/test/resources/coe.json dump`


# Test Fail
If the test fails, then it is because the tests depend on the co-simulation actually working. And the co-simulation does not work if there is not rabbitmq data I guess.

You will see that the error originates from `getData`:
```
[INFO] Running org.intocps.maestro.faultinject.rbmqfmuTest
[INFO] Model description path: /var/folders/n7/zgyjjt8n6hs6x9bzc_8zk340mzxzt6/T/rabbitmq14808352328824346406/resources/modelDescription.xml
[INFO] #
[INFO] # A fatal error has been detected by the Java Runtime Environment:
[INFO] #
[INFO] #  SIGSEGV (0xb) at pc=0x00000001383d2598, pid=52168, tid=9987
[INFO] #
[INFO] # JRE version: OpenJDK Runtime Environment (11.0.6+10) (build 11.0.6+10)
[INFO] # Java VM: OpenJDK 64-Bit Server VM (11.0.6+10, mixed mode, tiered, compressed oops, g1 gc, bsd-amd64)
[INFO] # Problematic frame:
[INFO] # C  [rabbitmq.dylib+0x36598]  FmuContainerCore::getData()+0x28
[INFO] #
[INFO] # No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
[INFO] #
[INFO] # An error report file with more information is saved as:
[INFO] # /Users/au443759/source/into-cps-association/fault-injection-maestro/faultinject-incubator/hs_err_pid52168.log
[INFO] #
[INFO] # If you would like to submit a bug report, please visit:
[INFO] #   https://github.com/AdoptOpenJDK/openjdk-support/issues
[INFO] # The crash happened outside the Java Virtual Machine in native code.
[ERROR] /bin/sh: line 1: 52168 Abort trap: 6           /Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home/bin/java -jar /Users/au443759/source/into-cps-association/fault-injection-maestro/faultinject-incubator/target/surefire/surefirebooter4743507061934419176.jar /Users/au443759/source/into-cps-association/fault-injection-maestro/faultinject-incubator/target/surefire 2021-08-06T11-39-59_733-jvmRun1 surefire13901404261153284098tmp surefire_117802997235224678343tmp
[INFO] # See problematic frame for where to report the bug.
[INFO] #
```
